---

name: tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2

      - uses: actions/setup-python@v4.7.0
        with:
          python-version-file: pyproject.toml

      - name: install dev dependencies
        run: pip install --user .[dev]

      - name: run tests
        run: python -mpytest

      - name: lint
        run: python -mflake8

...
 
